### ISSUE TITLE
Design Docs Sample State Review

### ISSUE THREAD

**Issue by rlim92** [kevinkusky/YubeToo_fullstack#2]
Hey Kevin! Sample state looking good. Some suggestions below.

**Sample State**
- [x] `authoredCommentIds` may be unnecessary for `users` as we will only really see comments from a video show page. 
- [x] consider adding `likedVideoIds` as a key in `users` for their show page. 
- [x] consider splitting `likeIds` in `videos` and `comments` into two keys of `likesCount` and `dislikesCount`. Youtube doesn't show the actual user that likes the video/comment so just grabbing the count should be sufficient. With these two `counts` can calculate `ratio` as well on the frontend. 
- [x] `likes` is not needed as a slice of state because Youtube does not use the liker information (other than for a user's show page ex. `liked videos`).

**Comment by kevinkusky** [comment]
- removed the list of 'authored comments' in favor of a list of 'liked videos'
- renamed convention for keeping track of likes/dislikes in the comments and videos state
- likes state removed as represented in comments as well as videos

All above issues should now be resolved.
