### ISSUE TITLE
Auth Functionality

### ISSUE THREAD

**Issue by kevinkusky** [kevinkusky/YubeToo_fullstack#5]
- Ability to create a new user
- Ability to log in a user
- Ability to sign out a user
- Navigation to the splash page via the website name on the Left side
- CSS of the sign up and log in forms

**Comment by rlim92** [comment]
Hey Kevin! The functionality is there but few things i noticed:

- [x] there is no demo login user button
- [x] the styling needs to be closer to Youtube's. Right now, the general format is there but it doesn't look enough like YouTube.
- [ ] the nav bar component should not be rendered when on either of the forms.

Good foundation, will need additional styling.
